server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: conta-passageiro-service
        uri: lb://conta-passageiro-service
        predicates:
        - Path=/conta-passageiro-service/**
      - id: passageiro-service
        uri: lb://passageiro-service
        predicates:
        - Path=/passageiro-service/**
      - id: passagem-service
        uri: lb://passagem-service
        predicates:
        - Path=/passagem-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

