server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: conta-passageiro-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/conta_passageiro_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 2211
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: conta_passageiro_service
    user: root
    password: 2211
springdoc:
  api-docs:
    path: conta-passageiro-service/v3/api-docs